import Head from 'next/head';
import AddTodoCard from '../components/cards/add-todo-card';
import TodosCard from '../components/cards/todos-card';
import Layout from '../components/layout';

export default function Home() {

  const getText = (text) => {
    console.log(text);
  }

  return (
    <>
      <Head>
        <title>todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout >
        <AddTodoCard onClick={getText} />
        <TodosCard className="" />
      </Layout>
    </>
  )
}
