import Head from 'next/head'
import Image from 'next/image'
import AddTodoCard from '../components/cards/add-todo-card'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css'

export default function Home() {

  const getText = (text) => {
    console.log(text);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout >
        <AddTodoCard onClick={getText} />
      </Layout>


    </div>
  )
}
